name: ci

on:
  push:
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        node-version:
          - 24.x
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm-setup
        uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2
        with:
          install: false
      - name: pnpm-store-dir
        id: pnpm-store-dir
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        name: pnpm-cache-setup
        id: pnpm-cache-setup
        env:
          cache-name: cache-pnpm-store
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          # prettier-ignore
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}-${{ matrix.node-version }}-
            ${{ env.cache-name }}-${{ runner.os }}-
            ${{ env.cache-name }}-

      - name: pnpm-install
        id: pnpm-install
        run: pnpm i

      - name: build
        run: pnpm dev

  automerge:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@73ec4cbb5e56df5591eae286972d5b2201ffe90f # v3
        with:
          target: "minor"
          exclude: "@types/node"
